### ISSUE TITLE
internal server error on web hosting publish

### ISSUE THREAD

**Issue by vslzl** [blackcity/Backload#100]
my file handler and handler methods /MyController/FileHandler

`[AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post | HttpVerbs.Put | HttpVerbs.Delete | HttpVerbs.Options)]
        public async Task<ActionResult> FileHandler()
        {
            try
            {
                // Create and initialize the handler
                IFileHandler handler = Backload.FileHandler.Create();

                // Attach event handlers to events
                //handler.Events.IncomingRequestStarted += Events_IncomingRequestStarted;
                //handler.Events.GetFilesRequestStarted += Events_GetFilesRequestStarted;
                handler.Events.GetFilesRequestFinished += Events_GetFilesRequestFinished;
                handler.Events.StoreFileRequestStarted += Events_StoreFileRequestStarted;

                // Init Backloads execution environment and execute the request
                handler.Init(HttpContext.Request);
                IBackloadResult result = await handler.Execute();

                // Helper to create an ActionResult object from the IBackloadResult instance
                return ResultCreator.Create(result);
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        private void Events_StoreFileRequestStarted(IFileHandler sender, Backload.Contracts.Eventing.IStoreFileRequestEventArgs e)
        {
            var file = e.Param.FileStatusItem;
            
            TempData["UploadRequest"] = true;
            TempData["LogoFilePath"] = file.ObjectContext;
            TempData["LogoFileName"] = file.FileName;
        }
`

also my backload config file is;

![bckld](https://cloud.githubusercontent.com/assets/17459982/16473085/e04f1e5a-3e72-11e6-93b4-237c08fdfd84.png)

    

also I give permission to ~/FirmLoads folder on plesk panel.

everything works cool on localhost but on server side it has 500 Internal server error on upload

you can test backload demo on [http://deneme.hazerantik.com.tr/ ](url)

Thanks for all helps.

**Comment by Auersberg** [comment]
This is very basic code and should work. By default the handler returns a 500 HTTP status on exceptions for security reasons. As I can see GET requests return a 200 OK HTTP status. 

In your handler you can change the exception handler to the following code. Open Fiddler and see what the request returns:
<pre>
catch (Exception e)
{
    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, e.Message);
}
</pre>

If this does not help enable tracing:
https://github.com/blackcity/Backload/wiki/Tracing

**Comment by vslzl** [comment]
my Web Hosting Firm said we use Persist UPLOAD on uploading mechanism of our servers, you should edit your codes for Persist UPLOAD component. so how can I do this on backload ?

**Comment by Auersberg** [comment]
I cannot help you with a Persist component. What error do you receive on uploads? GET requests seem to work with no errors. I think this is a permissions issue. Enable https://github.com/blackcity/Backload/wiki/Tracing and I can see the trace output online.
#77
