### ISSUE TITLE
Getting "Incorrect function"

### ISSUE THREAD

**Issue by dtsob75** [blackcity/Backload#105]
I am using version 1.9.3.1. 
I have an app that is trying to upload an image.  When it hits the server-side , it goes into the HandleRequest method and starts the IncomingRequesStarted method, but then fails with a message that says “Incorrect function. (Exception from HRESULT: 0x80070001)”. I have another app that does the same thing and it works fine.  I have compared all the code and it appears to be the same.
Not sure what to do next.  Any help would be appreciated.

**Comment by Auersberg** [comment]
This is not an issue related to the Backload component. When I search for "0x80070001" on the web it seems to be a problem with windows or .NET installation.

**Comment by dtsob75** [comment]
This ended up being an issue with my Google Chrome installation.  I initially tried it on MS Edge and it worked fine.  I had trouble updating chrome (another issue for another forum), but after I resolved that, it started working on the new version of Chrome, as well.
