### ISSUE TITLE
Why automatially rotate the uploaded image?

### ISSUE THREAD

**Issue by urlreader** [blackcity/Backload#107]
I'm using backload for image upload. It works fine. Here are the 2 lines in the Wev.backload.config

	<images width="3072" height="2304" dpi="96" canvasColor="#00ffffff" forceImageType="image/png" resizeMode="ratio" maxFileSize="4194304" />
	<thumbnails path="_thumbs" width="192" height="144" dpi="96" canvasColor="#00ffffff" resizeMode="ratio" imageType="image/png" />
	
However, I found that if upload an image whose width is < its height, the uploaded image will be automatically rotated. For example, the original image is (3072,2304), width 3072, after uploaded, the size becomes (2304,3072). It is rotated automatically.

Is there a way to keep the width/heigh ratio and without rotating it?

thanks

**Comment by blackcity** [comment]
Thanks for your message, we will check it.

**Comment by blackcity** [comment]
The image processing component passed the unit tests with success, but the resulting image failed to produce a valid image in the "ratio" resize mode. Thumbnails seem to be ok. Can you confirm this? 

What happens if you set "place" resize mode on images for testing purposes.

**Comment by urlreader** [comment]
it says "place" for resizeMode is invalid in images, however, it is valid for thumbnails. However, it always produces a valid image and thumbnail. I'm using c# .net.

The problem I have is as described in the original post. The image/thumbnail got rotated automatically if the original image's height > width.

I noticed that in the config, the width > height, maybe the component automatically rotate to 'fit' the config? which does not make much sense to me.

**Comment by blackcity** [comment]
"Place" should be available on images and thumbnails in the configuration. If it's marked as "not valid" you're maybe using an older version of the "~/Backload/Config/Web.Backload.xsd" schema file.

We made some tests and found some strange behavior. We've used an horizontally oriented image (landscape) as source. Then we rotated it directly in windows explorer (right click, rotate) with 90deg so it became vertically oriented. When we uploaded this image it rotated back for unknown reasons. It seems, that rotating it with windows explorer only sets some meta data, but does not save it correctly. After we opened the original image in Photoshop and rotated it with 90deg, the upload worked correctly. Maybe you can open your source image in your favorite image processing tool and save it back. Try it with thumbnails first.

What NuGet package version are you using?

**Comment by urlreader** [comment]
it is 1.9.3.1. The original images are actually captured by phone. if I rotate the phone (so height > width), take the picture, then move the picture to pc, the win10 shows the picture in the correct orientation. Maybe the image processing component does not use certain meta data.

**Comment by blackcity** [comment]
Thanks for this info, it helps a lot. Currently it seems this is a problem of PresentationCore as its providing incorrect values (dimension/orientation) with some images. Our code does not rotate any images. We definitely investigate this problem.
Can you send us one of your images (issues@backload.org)?

**Comment by urlreader** [comment]
I sent one sample image to your issues email, please check.

Thanks

**Comment by blackcity** [comment]
Thanks I have forwarded it to the dev.

**Comment by blackcity** [comment]
The problem with this image is that it is not physically rotated instead an EXIF tag has the orientation info (orientation: 90 cw). We have put it on our list and it will be handled in the coming release. Thanks for reporting this issue.

**Comment by Auersberg** [comment]
This is a way to rotate the image correctly before it is saved using server side events:
<pre>
void Events_StoreFileRequestStarted(IFileHandler sender, Contracts.Eventing.IStoreFileRequestEventArgs e)
{
    var file = e.Param.FileStatusItem;
    if (file.FileName.EndsWith(".jpg") || file.FileName.EndsWith(".jpeg"))
    {
         ImageHelper.RotateImageByExifOrientationData(file);
    }
}
</pre>
This is the ImageHelper class:
<pre>
public static class ImageHelper
{
    // Rotate the given image file according to Exif Orientation data
    public static RotateFlipType RotateImageByExifOrientationData(IFileStatusItem file)
    {
        // Rotate the image according to EXIF data
        var bmp = new Bitmap(file.FileStream);
        RotateFlipType fType = RotateImageByExifOrientationData(bmp);
        if (fType != RotateFlipType.RotateNoneFlipNone)
        {
            file.FileStream = new MemoryStream();
            bmp.Save(file.FileStream, ImageFormat.Jpeg);
            file.FileStream.Position = 0;
            file.FileSize = file.FileStream.Length;
        }
        return fType;
    }

    // Rotate the given bitmap according to Exif Orientation data
    public static RotateFlipType RotateImageByExifOrientationData(Image img, bool updateExifData = true)
    {
        int orientationId = 0x0112;
        var fType = RotateFlipType.RotateNoneFlipNone;
        if (img.PropertyIdList.Contains(orientationId))
        {
            var pItem = img.GetPropertyItem(orientationId);
            fType = GetRotateFlipTypeByExifOrientationData(pItem.Value[0]);
            if (fType != RotateFlipType.RotateNoneFlipNone)
            {
                img.RotateFlip(fType);
                // Remove Exif orientation tag (if requested)
                img.RemovePropertyItem(orientationId);
            }
        }
        return fType;
    }

    // Return the proper System.Drawing.RotateFlipType according to given orientation EXIF metadata
    public static RotateFlipType GetRotateFlipTypeByExifOrientationData(int orientation)
    {
        switch (orientation)
        {
            case 1:
            default:
                return RotateFlipType.RotateNoneFlipNone;
            case 2:
                return RotateFlipType.RotateNoneFlipX;
            case 3:
                return RotateFlipType.Rotate180FlipNone;
            case 4:
                return RotateFlipType.Rotate180FlipX;
            case 5:
                return RotateFlipType.Rotate90FlipX;
            case 6:
                return RotateFlipType.Rotate90FlipNone;
            case 7:
                return RotateFlipType.Rotate270FlipX;
            case 8:
                return RotateFlipType.Rotate270FlipNone;
        }
    }
}
</pre>

Source: http://stackoverflow.com/questions/27835064/get-image-orientation-and-rotate-as-per-orientation

**Comment by urlreader** [comment]
where IFileStatusItem is defined? Thanks

**Comment by blackcity** [comment]
You're using the 1.9.3.1 release. We've cleaned up some namespaces and renamed a few  interfaces and classes in the 2+ releases. 
In 1.9.3.1 the interface name is `IFileUploadStatusItem` within the `Backload.Contracts.Context` namespace. You can see the type in the `e.Param.FileStatusItem` object in your `StoreFileRequestStarted` event handler. The event signature has changed a bit too:
<pre>
// In 1.9.3 releases StoreFileRequestEventArgs is in the Backload.Eventing.Args namespace
void handler_StoreFileRequestStarted(object sender, Eventing.Args.StoreFileRequestEventArgs e)
{
    var file = e.Param.FileStatusItem;   // Backload.Contracts.Context.IFileUploadStatusItem
    if (file.ContentType.Equals("image/jpeg", System.StringComparison.InvariantCultureIgnoreCase))
    {
         ImageHelper.RotateByExifOrientation(file);
    }
}
</pre>

**Comment by urlreader** [comment]
if I use 

`// In 1.9.3 releases StoreFileRequestEventArgs is in the Backload.Eventing.Args namespace
void handler_StoreFileRequestStarted(object sender, Eventing.Args.StoreFileRequestEventArgs e)
{
    var file = e.Param.FileStatusItem;   // Backload.Contracts.Context.IFileUploadStatusItem
    if (file.ContentType.Equals("image/jpeg", System.StringComparison.InvariantCultureIgnoreCase))
    {
         ImageHelper.RotateByExifOrientation(file);
    }
}`

In RotateByExifOrientation, what we should change?

The file.FileStream does not exist anymore.

Or have to upgrade to backload 2?

thanks

**Comment by blackcity** [comment]
You are right. In this release the uploaded file data is in file.FileData. I would suggest you update to 1.9.3.6 where file.FileStream is available (make a copy of your project before). This release is the latest before 2.x. I have tested this release with the code above and your image and it worked.

The 2.x releases have a much cleaner code structure and do not pollute your project, but you need to change some code (see migration guide: https://github.com/blackcity/Backload/wiki/Upgrade-and-migration). A new NuGet package (v.2.2.2.7), which handles EXIF oriented images is ready but not published yet. So you may wait if you want to switch to 2.x.

**Comment by urlreader** [comment]
when you tested it, are you using 2.x? or 1.9.3.6? I upgraded to 1.9.3.6, but the image.PropertyIdList.Contains(ORIENTATION_ID) always false.

Just want to make sure 1.9.3.6 won't work, so I have tp upgrade to 2.x. 

If 1.9.3.6 works, then I do not want to upgrade to 2.x since too much related code change.

Thanks again.

**Comment by blackcity** [comment]
Seems I have used internal code with a higher revision number. I've created a new package from this code and uploaded it to NuGet so you can try it out.
http://www.nuget.org/packages/Backload/1.9.3.8

Manual installation:
- copy the NuGet package to your packages folder
- edit your packages.config file to set the new release number (1.9.3.8)
- reference the two assemblies (Backload.dll and Backload.Contracts.dll) in the packages lib folder.
- clean and rebuild your solution

**Comment by urlreader** [comment]
thank you very much, it works! I update the nuget package directly. appreciate the help.

Thanks again.

**Comment by blackcity** [comment]
Thanks for your feedback. We already included a similar solution in the current Developer packages.
https://github.com/blackcity/Backload/blob/master/Examples/Backload.Standard.2.2/Backload.AspNetCore.Demo.zip?raw=true

**Comment by ssolomon** [comment]
Just for the record, I'd like to add that I have seen the same issue with images taken on a phone, and see images auto-rotated.  Everything state here sound correct.  It appears to be an issue in how metadata about the image is created/saved and so the image is saved incorrectly.
