### ISSUE TITLE
Image with dpi=1 per inch doesn't scale well

### ISSUE THREAD

**Issue by mjmcginty** [blackcity/Backload#108]
A user uploaded an image to our site, apparently created or edited in photoshop, with dpi set to 1 and units set to inches.  Perhaps not surprisingly, it scaled very, very poorly.

I get this is anomalous, but ImageResizer and a desktop app called PolyView both scaled it adequately.

This is the original:

![2255-2275 eagle pkwy](https://cloud.githubusercontent.com/assets/12201845/19364670/f411b334-9143-11e6-9352-4abc93360a59.jpg)

This is the scaled output:

![2255-2275 eagle pkwy 1](https://cloud.githubusercontent.com/assets/12201845/19364765/5c4916b8-9144-11e6-84df-215cd78bdc49.jpg)

Any help?

TIA,
Mark McGinty

**Comment by mjmcginty** [comment]
On the server we have 2.1.5.5.  On my local machine I have 2.1.0.0, uploading the same image with the same settings scales correctly.  Those settings are <images resizeMode="maxratio" height="1000" width="1000" dpi="96" />

I brought a copy of 2.1.5.5 to my local system, changing only the DLLs, and reproduced the problem.  The output file was 119K, vs 411K output by the earlier version.

**Comment by mjmcginty** [comment]
And upon further tests I see the problem is gone in the latest version, which would render this a non-issue.

**Comment by blackcity** [comment]
Thanks for the feedback on this problem, it helps a lot. In the next release we update the image processing pipeline to fix issue #107 for images with EXIF orientation data.
