### ISSUE TITLE
.NET Core image processing

### ISSUE THREAD

**Issue by thebigwormhole** [blackcity/Backload#116]
Hi guys, thanks for this great tool. 

Image processing is available in all versions except .NET Core. When can we expect this feature in the .NET Core version?

**Comment by Auersberg** [comment]
As you may know, .NET Core has no built-in image processing. So, for .NET Core we will use a 3rd party library for this task. Currently, there is no production ready library, but we have some promising results with ImageSharp. It is in alpha state and has some problems with resolution and performance (compared to our image processing code in our full .NET Framework code). So, hopefully this will be resolved soon.

Within the next few days we'll publish a pre-release package for ASP.NET Core (and EF Core) which supports image processing.

**Comment by thebigwormhole** [comment]
That's amazing! We will test it when it its available. These messages  https://github.com/dotnet/corefx/issues/2020 had indicated that there will be no image processing in .NET Core, so we are very happy that you guys found a way to  integrate it as we desperately rely on this feature ;-)

**Comment by sunstatevallaycruiser** [comment]
RC seem to work pretty well. Only problem I have is that the image resolution isn't changing in the stored image. When users upload a 600dpi image we've configured to resize the image to 96dpi and max 1024x1024 size. Size works great, but resolution stays at 600 dpi. Is this a bug?

**Comment by Auersberg** [comment]
Yes, this was a bug. Now fixed.
