### ISSUE TITLE
JQueryFileUploadItem.extra.chunkInfo.totalParts is sometimes incorrect

### ISSUE THREAD

**Issue by michaelnero** [blackcity/Backload#120]
Hi. I have the following code to determine when a chunked file has completed uploading.

```
var totalUploadParts = fileUploadItem.extra.chunkInfo.totalParts;
var uploadedParts = fileUploadItem.extra.chunkInfo.uploadedParts;
if (totalUploadParts == uploadedParts)
{
    // Add to DB, enqueuer, etc.
}
```

However, the `totalParts` property sometimes changes values when I don't expect it to. For example, I have a file that is broken into 3 chunks. For the first 2 chunks, the `totalParts` property's value is 3. But for the last chunk the value is 15. This doesn't happen all the time. I have another file that is broken into 16 chunks and the `totalParts` property remains consistent, even on the last chunk.

Is this a bug? Or if I'm using this property incorrectly, what's the right way to determine if a chunked upload has completed.

For reference, my package references are below:

```
<package id="Backload.Core.Pro" version="2.2.2.5" targetFramework="net461" />
<package id="Backload.Plugin.AzureBlobStorage.Pro" version="2.2.2.5" targetFramework="net461" />
<package id="Backload.Pro" version="2.2.2.5" targetFramework="net461" />
```

**Comment by michaelnero** [comment]
For a little more context, this issue doesn't seem to happen when I upload a JPG file, but it does happen when I upload a PNG file.

**Comment by Auersberg** [comment]
This has technical reasons. JQuery File Upload plugin does not send the total number of chunks. So the total number of chunks must be calculated. This works fine for all chunks, but not the last one. This is why the number can be incorrect for the last chunk. 
This said, "fileUploadItem.extra.chunkInfo.complete" should be "true" when all files have been uploaded.

**Comment by michaelnero** [comment]
Ah, that did it. The `complete` property works consistently. Thanks for your help!
