### ISSUE TITLE
Slow download with Entity Framework

### ISSUE THREAD

**Issue by Boeckie** [blackcity/Backload#126]
Dear,

  I'm using with Backload with Entity Framework and noticed that Backload executes the following query before a download is started:

SELECT 1 AS "C1", "Extent1"."Id", "Extent1"."RowId", "Extent1"."DownloadPath", "Extent1"."Name", "Extent1"."Original", "Extent1"."Type", "Extent1"."Size", "Extent1"."UploadTime", "Extent1"."Data", "Extent1"."Preview", "Extent1"."Path", "Extent1"."Meta", "Extent1"."DossierBijlage_Id" FROM "dbo"."Files" AS "Extent1"

  As all data in the files table is selected, this obviously gets *very* slow when a lot of files have been uploaded.

  Any idea what is going wrong?

Thanks,
Bart

**Comment by Auersberg** [comment]
Strange indeed. We'll need to investigate.
What does your GET method look like in your DBContext class? This is the the default GET method:

<pre>
public IEnumerable<IBackloadStorageProviderFile> Get(ICommandArgument args)
{
   return this.Files;
}
</pre>

**Comment by Boeckie** [comment]
thanks for the feedback

`        /// <summary>
        /// Returns a list of files stored in the database matching the criteria in args
        /// </summary>
        /// <param name="args">Provides command parameters</param>
        /// <returns>A list of files </returns>
        public IEnumerable<IBackloadStorageProviderFile> Get(ICommandArgument args)
        {
            return this.Files;
        }
`

**Comment by Auersberg** [comment]
We still investigating. In the meantime you may use somthing like this:

<pre>
public IEnumerable<IBackloadStorageProviderFile> Get(ICommandArgument args)
{
    // Specific file is requested
    if (args.CommandType == CommandArgumentType.GetFileById)
    {
        return this.Files.Where(f => f.Id == args.FileId);
    }

    return this.Files;
}
</pre>

Maybe there is a different `CommandArgumentType` in your request, so set a breakpoint and see if its `CommandArgumentType.GetFileById`. The property `args.FileId` has the row id for the file.

**Comment by Boeckie** [comment]
Thanks! Considerable performance improvement: from 30 seconds to less than 1 second!

CommandArgumentType in my request is  CommandArgumentType.GetFileById

**Comment by Auersberg** [comment]
Thanks for reporting this issue.

**Comment by Boeckie** [comment]
pleasure

fix is installed and will be tested by customer, if you're interested, I'll post the feedback

**Comment by Auersberg** [comment]
Of course I will 😄

**Comment by Boeckie** [comment]
customer is very happy - minutes after testing I got the request to move to production!

thanks!

**Comment by Auersberg** [comment]
Very cool!
