### ISSUE TITLE
Possible to set "filesRoot" from code?

### ISSUE THREAD

**Issue by UweKeim** [blackcity/Backload#131]
Is it possible to set the value of the `filesRoot` attribute of the [`<fileSystem>` configuration element](https://github.com/blackcity/Backload/wiki/Configuration#filesystem-configuration-element) from within code?

I.e. I do not want to set it via "Web.Backload.config" but programmatically, e.g. from within "Global.asax.cs".

Possible?

**Update for clarification:**

Of course, I do not want to modify the physical "Web.Backload.config" file, but I want to tell the "Backload runtime" to use a value that I pass from code for its in-memory-representation of the `filesRoot` attribute.

**Comment by Auersberg** [comment]
Use server side events:
https://github.com/blackcity/Backload/wiki/Server-side-events

The first event fired in the execution pipeline is the `ConfigurationLoaded` event:
https://github.com/blackcity/Backload/wiki/Server-side-events#configurationloaded-event

**Comment by UweKeim** [comment]
Works, thanks a lot.
