### ISSUE TITLE
Azure File upload

### ISSUE THREAD

**Issue by ginoburrr** [blackcity/Backload#133]
Hi, 

I am successfully uploading large file to azure using chunking. 

I was wondering how do I change the container that the file will save in during runtime. 

Eg:
`<azureBlobStorage uploadContainer="uploads" connectionString="XXXXXX" /> `
want to change "uploads" to **project2** if im on project 2 or **project4** if im on project 4,

**Comment by quartilesoftware** [comment]
I have the same question. 

Has anyone been able to work out how to dynamically change the target Azure container at runtime? I have a project with multiple tenants and separating their storage into separate containers is essential.

**Comment by ginoburrr** [comment]
Hi, 

I ended up going to another plug (dropzone) which now support chunking

**Comment by quartilesoftware** [comment]
Hi,

Thanks. I've now reached the same conclusion myself: I'm going to use something other than Backload.

**Comment by gravitykillz420** [comment]
?? I’m lost
