### ISSUE TITLE
500 Error when there is an Origin Header

### ISSUE THREAD

**Issue by BruceGilham** [blackcity/Backload#53]
I'm getting a 500 error when I try to do a post using chrome.  I narrowed it down to the Origin Header.  When that header is included the server returns a 500.  Taking that header out and sending everything else exactly the same will post and the server returns a 200.  

I tried turning on all CORS settings for IIS, ASP.Net MVC, and Backload but I'm still getting the 500.  

Any ideas or suggestions?

Thanks

**Comment by Auersberg** [comment]
I think you are using release 2.0. CORS is included in release 2.1+.
[Release notes](https://github.com/blackcity/backload/wiki/Release-notes#releases)

George Auersberg

**Comment by BruceGilham** [comment]
My Client just bought the pro version 2 days ago.  We needed it for the chunk uploads.  Where should I tell him to get the 2.1 bits?

**Comment by BruceGilham** [comment]
I just confirmed that we're using 2.1.0.5 and getting that error.  I can replicate it by doing a post with fiddler and adding/removing the Origin header.  I am going to see if there's some other MVC CORS settings that I may have missed.

**Comment by Auersberg** [comment]
I need some more information. Can you send an email to this [address](https://github.com/blackcity/Backload#direct-contact)? Within this email please tell me the name of your client.

**Comment by BruceGilham** [comment]
Email sent
