### ISSUE TITLE
keepOrgFileNames causes exception

### ISSUE THREAD

**Issue by MrStepson** [blackcity/Backload#54]
In the latest version setting keepOrgFileNames="true" and uniqueFileNames="true" causes "Exception occured while storing the file". I have reprduced the issue with Backload.Standard.2.0.Full demo project (upload file via jQuery File Upload Demo page). I have notice that my file and thumb are stored succesfully, but mappings sub-folder is empty, so I guess the error is related to mapping saving.

**Comment by Auersberg** [comment]
Instead of creating the mapping file a folder is created in this release. This issue is fixed in release 2.1 which is not public yet.

**Comment by Auersberg** [comment]
Fixed in Interims release 2.0.1.0 and in the [demo solution](https://github.com/blackcity/Backload/releases/download/v2.0.0.0/Backload.Standard.2.0.Full.zip).
