### ISSUE TITLE
Chunked files aren't merged

### ISSUE THREAD

**Issue by igorlimonm** [blackcity/Backload#55]
Hi,
I have a issue when deploy on production.
Uploading big file(~400MB) handler didn't create folder to storing chunked files.
On each request create new file if uniquefilename is true or overitte prevision chunked file.
Locally on IIS and IIS express is worked OK, folder with chunked files is created and after last chunk file is generated and folder is deleted.

On client side I use Jquery Upload file.

Bellow you can see code for saving file.

Thanks,
Igor.
                // Create and initialize the handler
                IFileHandler handler = Backload.FileHandler.Create();
                handler.Init(HttpContext.Request);
                // Call the execution pipeline and get the result
                IBackloadResult result = await handler.Execute();
                // Helper to create an ActionResult object from the IBackloadResult instance
                return ResultCreator.Create(result);

**Comment by Auersberg** [comment]
https://github.com/blackcity/backload/wiki/faq#everything-works-locally-but-not-on-the-production-server
and
https://github.com/blackcity/Backload/wiki/editions
