### ISSUE TITLE
File upload doesn't working on remote server

### ISSUE THREAD

**Issue by evgeniiv** [blackcity/Backload#56]
When I try to upload file on server locally, all works fine. But when I trying to upload file on the same server from remote computer I heve the null reference exception - on handler.Service.POST or handler.Services.Core.

var handler = Backload.FileHandler.Create();
 handler.FileStatus = await handler.Services.POST.GetPostedFiles(); // null reference Exception

Could anybody help me?

**Comment by angyy10** [comment]
I am also having this issues

**Comment by angyy10** [comment]
OK, I found the root cause.
Turns out "handler.Services.POST.GetPostedFiles()" is Pro/Enterprise features.
Either you purchase the license or try to process the POST variables yourself.
