### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by sean-antony** [blackcity/Backload#59]
Hi, 

I tried uploading my MVC project to a server, but I am not able to upload anything there. It is working locally though. I get the following error: 

http://[servername]/CustomEvents/FileHandler?plugin=PlUpload&objectContext=3E8A03244079 Failed to load resource: the server responded with a status of 404 (Not Found)

I have only added these lines to my Web.Backload.config file:

fileSystem filesRoot="~/Uploads" 

images width="1280" height="1024" dpi="96" canvasColor="#00000000" forceImageType="image/jpeg" resizeMode="ratio" maxFileSize="1073741824" 

What am I doing wrong?

Thanks,
Sean

**Comment by Auersberg** [comment]
This is a bit hard to say. Often you work locally with the ip address: 
http//[ip-address]/CustomEvents/FileHandler?...
But on IIS this is: http://[servername]/[appname]/CustomEvents/Filehandler?...

In your JavaScript configuration file for PlUpload you maybe have to set the correct path (add the application name part?). At least, you have to find out what the correct endpoint for the component on your server is.

**Comment by sean-antony** [comment]
Thanks Auersberg. It is uploading now. It was just a folder permission issue on the server.
