### ISSUE TITLE
500 Internal Server Error - Not able to upload > 5MB

### ISSUE THREAD

**Issue by sean-antony** [blackcity/Backload#60]
Hi,

When I try to upload a file larger than 5MB I get 500 Internal Server Error. I have already set maxRequestLength="2097152" and maxAllowedContentLength="2147483648" in my web.config file. 

I am using the plUpload UI sample on my server. I have set max_file_size: 1000mb & chunk_size: 5mb. Am I missing any configuration for Backload that will allow the server to upload more than 5mb?

Thanks,
Sean

**Comment by Auersberg** [comment]
In general, chunked file support is currently a Pro feature. But it should work on a local dev machine for testing and evaluation.
https://github.com/blackcity/backload/wiki/editions

Do you work on a local machine and have you tested to upload chunked files with the other client side plugins (e.g. jQuery File Upload Plugin)? Does it work with the other plugins?
