### ISSUE TITLE
Internal Server Error on Production Site

### ISSUE THREAD

**Issue by kiwidjb** [blackcity/Backload#61]
Have been getting Internal Server Error on uploads on my production environment only (file uploads but fails with the error at the end. I am using shared hosting on GoDaddy and have enabled Full Trust.

To determine if it was a coding issue, I pushed the Backload Demo site onto my server and ran the jQuery demos (Basic Plus UI). Same issue - you can see at http://turkanz.net/home/basicplusui after selecting a file and uploading.

This now sounds like its either an environmental issue with the hosting or a paid only feature in the demo that I was also using. Can you please clarify - am happy to purchase if this is the case but there is no point if my hosting company doesn't support the requirements.

Many Thanks
John

**Comment by blackcity** [comment]
It's difficult to sort out your problem from here. As I can see in Fiddler GET requests work as expected. POST requests return with a 500. 

DELETE reqests return a 405 (Method Not Allowed) with this header:
HTTP/1.1 405 Method Not Allowed
Allow: GET, HEAD, OPTIONS, TRACE
Content-Type: text/html
Server: Microsoft-IIS/8.5
X-Powered-By: ASP.NET
X-Powered-By-Plesk: PleskWin

It seems POST and DELETE requests are not enabled or disabled by default, so you can try to add the following settings to the `system.WebServer` element in your `Web.config` file:
https://raw.githubusercontent.com/blackcity/Backload/master/Examples/Backload.Standard.1.9/Example01/Web.config

If this not helps, add tracing support (example 13) to your `Web.config` file and add a trace listener. With Glimpse (Nuget Glimpse.Core) you can view the trace output online. After you added Glimpse, you can send me a message.

**Comment by kiwidjb** [comment]
Found the problem - with some GoDaddy permissions. Worked with them to resolve. Thanks for your suggestions which got me on the right path.
