### ISSUE TITLE
WebApi controller doesn't work with remote requests

### ISSUE THREAD

**Issue by MrStepson** [blackcity/Backload#62]
I have evaluated Backload 2.0 WebApiDemo demo and noticed that this code works with local server requests only. Remote requests causes exception since handler.Services.GET/POST/DELETE are nulls. As I can see in disassembled code, service creation purposely enabled for local requests only, but I couldn't find any documentation about this.
```c#
internal ServiceHub(IFileHandler handler)
{
....
	 if (((WebConfig)handler.get_Context().get_Configuration()).CanTrace)
	{
		this._getServices = new GETServices(this._core);
		this._postServices = new POSTServices(this._core);
		this._delServices = new DELETEServices(this._core);
	}
...
}
```

**Comment by helgans** [comment]
Calling API functions is a Pro feature in the 2.0 releases.

https://github.com/blackcity/Backload/wiki/editions#features-only-available-in-proenterprise-editions
