### ISSUE TITLE
Big images upload thumbnail problem

### ISSUE THREAD

**Issue by sametkat** [blackcity/Backload#69]
Hi,
I use backload in my image upload project. if I upload <100 mb image, file upload and thumbnail creation is successfully. >100 mb images upload is complete but thumbnail creation is failed. Backload returns Internal server error. I am using MVC5 and in code section (backloadController) catch block says "No imaging component suitable to complete this operation was found" .
How can I fix this problem.
thank you

**Comment by Auersberg** [comment]
Hard to say. The error message is thrown from WPF. What image type are you uploading and is the thumbnail created as png? Can you provide the file as download?

**Comment by sametkat** [comment]
I upload jpg images and thumbnail is png. I provide only upload. İf ı disable thumbnail creation over web config file ( thumnailpath="" ) , after upload javascript send exception and says unexpected end of file json parse error.

**Comment by Auersberg** [comment]
I assume you have the latest release installed. You store the files into the file system, not database or cloud and you do not have base64 (embedded data urls) enabled as thumbnailUrl. Is this true? If you disabled storing thumbnails and thumbnailUrlPattern is not set to "base64", image processing (creation of thumbnails) Is completely bypassed. So, the problem must occur before.

What you can do:
Can you post your config file? 
Enable tracing in Verbose mode (tracelevel) and send me the trace log file (g.auersberg /at/ gmail.org)
Send me a Fiddler session archive (.saz).

**Comment by Auersberg** [comment]
One more thing: What happens when you set the maxFileSize option of the image configuration element:
 \<images maxFileSize="50000000" /> \

This setting will only try to create thumbnails for images up to 50mb.

**Comment by Auersberg** [comment]
The current public stable release 2.1.5.4 includes an optimization within the image processing code. The new code reduces memory consumption while processing the image. It has been successfully tested with our 500mb reference image file and maybe solve your problem.

**Comment by sametkat** [comment]
Hi, 
maxFileSize attribute solved my problem. Thank you very much for your help. 
I wish you continued success.
