### ISSUE TITLE
ClientFilesElement not working 

### ISSUE THREAD

**Issue by amuagarwal** [blackcity/Backload#70]
Config File Entry
 <clientFiles styles="~/LocalCDN/Content/FileUpload/css/" scripts="~/LocalCDN/Scripts/FileUpload/"/>

using code 
var cFiles = new ClientFilesElement();
 cFiles.Scripts is giving the default value "~/Backload/Client" Not the value mentioned in the "Web.Backload.config" file

I tested the same thing with the example downloaded and that also have same issue.

Thanks in Advance.

**Comment by Auersberg** [comment]
Hi, up to release 2.1 the `clientFiles` config element is available after the handler has been initialized:

    IFileHandler handler = Backload.FileHandler.Create();
    
    // Init Backloads execution environment and execute the request
    handler.Init(HttpContext.Request);
    var cFiles = handler.Context.Configuration.ClientFiles;

**Comment by amuagarwal** [comment]
Hi

Thanks for the update. But the issue which i am facing is i need this values in PostApplicationStartMethod and there i can't get HttpContext.Request object please help me on the same.

Thanks

**Comment by Auersberg** [comment]
The reason I wrote "up to release 2.1" in my prevoius post was that from release 2.2 on we removed dependency on `HttpRequest` completely, but this doen't help you now. If you want to read the configuration you have two choices: 

**Read and parse the XML file**
Choose the method you prefer. You can use "~/config/Web.Backload.xsd" as schema.

**Create an instance of  the `Backload.Configuration.BackloadSection` class**

    public class DemoClass
    {
        private static Backload.Configuration.BackloadSection _config = new Configuration.BackloadSection();
    
        public DemoClass()
        {
            var clientFiles = _config.ClientFiles;
        }
    }

Note that I used the static modifier to avoid loading and parsing the configuration on every request.

**Comment by amuagarwal** [comment]
the only way by which i get it works is:

 var cFiles = (BackloadSection)ConfigurationManager.GetSection("backload");

even creating the instance giving me the default values not the values which are there in the xml.

**Comment by Auersberg** [comment]
> the only way by which i get it works is:
> var cFiles = (BackloadSection)ConfigurationManager.GetSection("backload");

This is ok. Under the hood, the same code is used when creating an instance of BackloadSection. And don't forget to make the variable static when using this in a web environment.

**Comment by amuagarwal** [comment]
Thanks a lot for your support and prompt responses. I need it only for one time so its private variable next to the use :)
