### ISSUE TITLE
Error trying to use objectContext

### ISSUE THREAD

**Issue by chm2305** [blackcity/Backload#75]
Hi,
I looking for a way to get a separate folder for each user logged in – and that should be accomplished by objectContext – but no…
I have tried every method in example 6 but it keeps coming back with “Internal server error” – and behind the error (as far as I can debug) the error says "Index (zero based) must be greater than or equal to zero and less than the size of the argument list."
Please enlighten me – what am I doing wrong?

**Comment by Auersberg** [comment]
This is an unusual error. In the Visual Studio output window you should get more info where the code causes an error. In my opinion this has nothing to do with objectContext. There must be an other cause for this. 
Standard tracing level is information in Visual Studio. You can set it to "verbose" (see https://github.com/blackcity/Backload/wiki/Tracing).

All examples in the [demo package](https://github.com/blackcity/Backload/blob/master/Examples/Backload.Standard.2.2/Backload.FileSystem.Demo.zip?raw=true) are using objectContext.

**Comment by chm2305** [comment]
It Works fine with this configuration:
<?xml version="1.0"?>
<backload eventing="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:name="urn:backload-schema" xsi:noNamespaceSchemaLocation="Config\Web.Backload.xsd"
            uniqueFileNames="false"
            keepOrgFileNames="false"
            getInclSubFolders="true"
   deleteUrlPattern="http://local.ip/fileupload/{name}"
   filesUrlPattern="http://local.ip/fileupload/{name}"
   thumbsUrlPattern="http://local.ip/fileupload/_thumbs/{name}.png"
  >
  <license licensee="info@ngsn.dk" licenseKey="6EE5DD4E-A945-87CD-7AD2-8B0953D4E27C" />
  <fileSystem filesRoot="\\XXX.YYY.ZZZ.NNN\Fileupload"  />
</backload>
But as soon as i add this line to the view:
<input type="hidden" name="objectContext" value="user123" />
then i get the error...?!?

**Comment by chm2305** [comment]
It Works fine with this configuration:
 <?xml version="1.0"?>
 <backload eventing="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:name="urn:backload-schema" xsi:noNamespaceSchemaLocation="Config\Web.Backload.xsd"
 uniqueFileNames="false"
 keepOrgFileNames="false"
 getInclSubFolders="true"
 deleteUrlPattern="http://local.ip/fileupload/{name}"
 filesUrlPattern="http://local.ip/fileupload/{name}"
 thumbsUrlPattern="http://local.ip/fileupload/_thumbs/{name}.png"

 But as soon as i add this line to the view:

 then i get the error...?!?

**Comment by chm2305** [comment]
It Works fine with this configuration:
 <?xml version="1.0"?>
 <backload eventing="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:name="urn:backload-schema" xsi:noNamespaceSchemaLocation="Config\Web.Backload.xsd"
 uniqueFileNames="false"
 keepOrgFileNames="false"
 getInclSubFolders="true"
 deleteUrlPattern="http://local.ip/fileupload/{name}"
 filesUrlPattern="http://local.ip/fileupload/{name}"
 thumbsUrlPattern="http://local.ip/fileupload/_thumbs/{name}.png"


`<input type="hidden" name="objectContext" value="user123" />`


 But as soon as i add this line to the view:

 then i get the error...?!?

**Comment by Auersberg** [comment]
As I see, you are using an external storage path (unc path). Instead of manipulating the urlPatterns, try using webFilesRoot. See: https://github.com/blackcity/Backload/issues/74. This maps the virtual path name configured in IIS ("fileupload") to the physical path ("\\xxx\yyy\").
In your case: webFilesRoot="fileupload", filesRoot="\\xxx\yyy\". This is resolved to "http://local.ip/fileupload/". And dont forget to remove the urlPattern in case you use webFilesRoot.

**Comment by chm2305** [comment]
`<?xml version="1.0"?>
<backload eventing="true" 
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
          xmlns:name="urn:backload-schema" 
          xsi:noNamespaceSchemaLocation="Config\Web.Backload.xsd"
          webFilesRoot="Fileupload"
  >
  <license licensee="xxx@yyy.dk" licenseKey="...." />
  <fileSystem filesRoot="\\192.168.123.60\Fileupload"  />
</backload>`
this is whatit looks like now - and i still get "internal server error".
Any ideas?

**Comment by Auersberg** [comment]
Looks good now with one exception:

#74 
> In your external storage scenario you set  webFilesRoot  and  filesRoot  to the same values like you do in IIS Manager to add a virtual directory to an external storage location. This can also be an unc path. Note: In the current release  filesRoot  must end with a backslash (like in my example above) when using an FQ path.

You may set a trailing backlslash filesRoot="\\server\path\"
