### ISSUE TITLE
Error application WebForms - The type or namespace name 'Configuration' does not exist in the namespace 'Backload'

### ISSUE THREAD

**Issue by andrecesco** [blackcity/Backload#76]
Hi.

I'm with a problem in creating a .Net WebForms application , then import using NuGet . There was a compile error

Error: The type or namespace name 'Configuration ' does not exist in the namespace ' BackLoad ' (are you missing an assembly reference ? ) .

You can use the " BackLoad " for WebForms ? And where can I find examples or projects for WebForms

thank you

**Comment by Auersberg** [comment]
Try the new 2.2 demo package with 20 demos. There is also a WebForms and an HTML demo.
https://github.com/blackcity/Backload/blob/master/Examples/Backload.Standard.2.2/Backload.FileSystem.Demo.zip?raw=true

**Comment by andrecesco** [comment]
Auersberg.

My problem is with **using Backload.Configuration;**

Witch shows this error: "Error: The type or namespace name 'Configuration ' does not exist in the namespace ' BackLoad ' (are you missing an assembly reference ? ) ."

My project is a WebForms. I downloaded all the files using "nuget".

Whats wrong?

Thanks for help

**Comment by andrecesco** [comment]
The file that where is "using Backload.Configuration", is "BackLoad/Bundles/BackloadBundles.cs"

**Comment by Auersberg** [comment]
I think you can remove this line of code, because it is not used in the newer releases of Backload. But the error may points to another problem. Do you see the two assemblies Backload.dll and Backload.Contracts.dll in your rereferences.

**Comment by andrecesco** [comment]
Hi, Auersberg.

The project that you sent me , it's working , but it is in the framework version 4.5, my project is in version 4.0 .

You have a project in 4.0 to help me ?

thank you

**Comment by Auersberg** [comment]
You can download the NET 4 demo package here:
https://github.com/blackcity/Backload/blob/master/Examples/Backload.Standard.2.1.Full/Backload.Demo.Net4.zip?raw=true
