### ISSUE TITLE
Internal Server Error on Published

### ISSUE THREAD

**Issue by vslzl** [blackcity/Backload#77]
I used backload on my MVC4 project. Everything goes fine on localhost, I can upload images but on server side, it doesn't works, Upload ends with internal server error so I tried to publish the original demo solution to server. You can check from http://dene.mirketmedya.com/Home/CustomWebApi it is still the same error. thank you for your helps.

**Comment by Auersberg** [comment]
Can you provide your Web.Backload.config settings? Maybe you're using a Pro feature?
https://github.com/blackcity/Backload/wiki/Configuration
https://github.com/blackcity/Backload/wiki/editions

**Comment by vslzl** [comment]
```
<?xml version="1.0"?>

<backload eventing="true" storageContext="Filesystem" xsi:noNamespaceSchemaLocation="Config\Web.Backload.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:name="urn:backload-schema">

 
  <fileSystem filesRoot="~/Uploads" />

</backload>

```
This is Web.Backload.config settings, This is base configurations, I didn't change anything as I said I published whole demo to my server to see if I have an issue with my own codes. But Backload Demo is also return with same error.

**Comment by vslzl** [comment]
![screen](https://cloud.githubusercontent.com/assets/17459982/13301878/c8e188e2-db4f-11e5-9c3f-9aeeec00a8e0.PNG)

Here is a screenshot with Firefox Web Console

**Comment by Auersberg** [comment]
500 Internal Server Error is the default error code. You need to get more information. The easiest way is to return the exception message in ~/Backload/BackloadController.cs. Within the catch block you may write this code:

       catch (Exception e)
       {
           return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, e.Message);
        }

Maybe a permissions issue? If this does not help and you do not have direct access to the server, you may write the trace output the a file. https://github.com/blackcity/Backload/wiki/Tracing
