### ISSUE TITLE
Backload customize model

### ISSUE THREAD

**Issue by thanh1259** [blackcity/Backload#79]
How do i add more fields to table Files? And how to insert data accordingly?

**Comment by Auersberg** [comment]
See examples 5 and 6 of the database demo package:
https://github.com/blackcity/Backload/blob/master/Examples/Backload.Standard.2.2/Backload.Database.Demo.zip

In short: Use the Entity Framework and build your model as you need it. The Backload component exchanges data with your custom DBContext class by an IBackloadStorageProviderFile interface. You can map the provided data to the properties of your entity. See the examples and set a breakpoint in the methods of the ~/Models/FilesContext.cs class and you see how it works.
