### ISSUE TITLE
How can I handle(prevent, show message) upload for files with the same name when uniqueFileNames=false ?

### ISSUE THREAD

**Issue by AndreiNateasin** [blackcity/Backload#80]
I have tried to change default behavior like this, but still I am missing something. Default was "overwrite"
_handler.Context.Configuration.FileExistsBehaviour = FileExistsType.error;

**Comment by blackcity** [comment]
Currently you should use uniqueFileNames and optionally keepOriginalFileNames to prevent overriding of existing files. The feature was implemented in the current release 2.2.1.5. I send you a link tomorrow.
