### ISSUE TITLE
Error on download file using {Backload} url pattern for Blob storage

### ISSUE THREAD

**Issue by AndreiNateasin** [blackcity/Backload#81]
Configuration:
deleteUrlPattern="{Backload}"
filesUrlPattern="{Backload}

Error:
"Index was out of range. Must be non-negative and less than the size of the collection.\r\nParameter name: index","ExceptionType":"System.ArgumentOutOfRangeException","StackTrace":"   at Backload.FileHandler.

**Comment by Auersberg** [comment]
Fixed in release 2.2.2.0

Thanks for reporting
