### ISSUE TITLE
Licensing info

### ISSUE THREAD

**Issue by DaveDiest** [blackcity/Backload#85]
Hello,  

I see # of websites listed as part of your packages.  What does that refer to?     What I need is the ability to use Backload on multiple sites, could be 10 or more that we host or deploy at our customer sites.  What license do we need to purchase for this?

Thanks

**Comment by blackcity** [comment]
You can choose the Pro Edition. If you have special requirements for different customers, I suggest to select the Enterprise Edition because the source code is included.

**Comment by DaveDiest** [comment]
Enterprise says 3 web sites included.   Does that mean we can only use for three websites?

**Comment by blackcity** [comment]
I see that this info on the website is misleading. The Enterprise license includes unlimited websites.

**Comment by DaveDiest** [comment]
Thanks for your quick response and info
