### ISSUE TITLE
Looking for license for Enterprise version

### ISSUE THREAD

**Issue by DaveDiest** [blackcity/Backload#86]
Hello,

Can you provide the license terms for the Enterprise version for our review.  I found the standard license and since we are looking at the Enterprise version we need to review the license for the paid version.

**Comment by blackcity** [comment]
You can download the Pro/Enterprise license here:
https://raw.githubusercontent.com/blackcity/Backload/master/Examples/license.txt
There is no much difference compared to the Standard license.
