### ISSUE TITLE
IndexOutOfRangeException on handler.Execute()

### ISSUE THREAD

**Issue by Abe-Froman** [blackcity/Backload#87]
I'm using pretty much the out-of-box, simple setup to pilot the app for our use. When I run my MVC app with Backload locally, everything is working fine. When I publish to an IIS server to test, I'm getting an exception from within the IFileHandler.Execute() method. The full exception (obtained through debugging remotely) is here:

    {Index (zero based) must be greater than or equal to zero and less than the size of the argument list.}
        Data: {System.Collections.ListDictionaryInternal}
        HResult: -2146233033
        HelpLink: null
        IPForWatsonBuckets: {140711452006959}
        InnerException: null
        IsTransient: false
        Message: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
        RemoteStackTrace: null
        Source: mscorlib
    InnerException: null
    IsTransient: false
    Message: "Index (zero based) must be greater than or equal to zero and less than the size of the argument list."
    RemoteStackTrace: null
    Source: "mscorlib"
        InnerException: null
    IsTransient: false
    Message: "Index (zero based) must be greater than or equal to zero and less than the size of the argument list."
    RemoteStackTrace: null
    Source: "mscorlib"
    StackTrace: "   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)\r\n   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)\r\n   at System.String.Format(IFormatProvider provider, String format, Object[] args)\r\n   at System.Diagnostics.TraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String format, Object[] args)\r\n   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String format, Object[] args)\r\n   at Backload.Context.Tracing.TraceManager.WriteTraceInfo(String trace, String type, String[] vars, Boolean flush)\r\n   at Backload.Context.Tracing.TraceManager.WriteTraceInfo(String trace, String id, String var1)\r\n   at Backload.Services.CoreServices.<>c__DisplayClasscc.<CreateSubFolders>b__cb()\r\n   at System.Threading.Tasks.Task`1.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Backload.Services.CoreServices.<CreateSubFolders>d__ce.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Backload.Services.CoreServices.<PostFilesInternal>d__e4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Backload.Services.ServiceHub.<POSTHandler>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Backload.FileHandler.<Execute>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Backload.FileHandler.<Execute>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Backload.Controllers.BackloadController.<FileHandler>d__0.MoveNext()"
Here's my FileHandler() action:

    public async Task<ActionResult> FileHandler()
    {
        try
        {
            // Create and initialize the handler
            IFileHandler handler = Backload.FileHandler.Create();

            handler.Init(HttpContext.Request);

            // Attach any event handlers needed
            handler.Events.DeleteFilesRequestStartedAsync += Events_DeleteFilesRequestStartedAsync;
            
            // Call the execution pipeline and get the result
            IBackloadResult result = await handler.Execute(); // <--- This line throws
            
            // Helper to create an ActionResult object from the IBackloadResult instance
            return ResultCreator.Create(result);
        }
        catch
        {
            return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
        }
    }

This is web.backload.config

    <?xml version="1.0"?>
    <backload xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:name="urn:backload-schema" xsi:noNamespaceSchemaLocation="Config\Web.Backload.xsd" getInclSubFolders="true" eventing="true">
        
        <fileSystem filesRoot="~/Uploads" />
        <images maxFileSize="2000000000" />
        <thumbnails path="" />
    </backload>

Here is the javascript handling the client-side work:

    $('#fileupload').fileupload({
        //dataType: 'json',
        autoUpload: true,
        url: fileUploadHandlerUrl, //backload                
        maxChunkSize: 50000000, // 50MB chunks
        add: function (e, data) {
            attachmentCount++;
            attachmentNumbers[data.files[0].name] = attachmentCount;
            $.each(data.files, function (index, file) {
                $("#filesTable").show();
                var tr = document.createElement('tr');
                var td1 = document.createElement('td');
                td1.className = 'col-md-6';
                td1.id = "filename" + attachmentCount;
                var td2 = document.createElement('td');
                td2.className = 'col-md-3';
                var td3 = document.createElement('td');
                td3.className = 'col-md-3';
                $(tr).append(td1).append(td2).append(td3);
                $(td1).append(file.name);
				$(td2).append(NormalizeFilesize(file.size));
				$(td3).append(remove_btn.clone(true).data(data));
				$('#tbodyAttachments').append(tr);

				var size = $("#tbodyAttachments tr").size();
				if (size < 1) {
					$("#files_list").addClass('hide');
				}
				else {
					$("#files_list").removeClass('hide');
				}

				data.context = $('#filename' + attachmentNumbers[data.files[0].name]).text(data.files[0].name + ': Uploading...').replaceAll($('#filename' + attachmentNumbers[data.files[0].name]));
				data.submit();
			});
		},
		done: function (e, data) {
			data.context.text(data.files[0].name + ': Upload finished');// + $('<button class="btn btn-danger cancel pull-right"><i class="icon-ban-circle icon-white"></i><span>Delete</button>'));
			$('#filename' + thisAttachmentNumber).css('color', 'white');
			$('#filename' + thisAttachmentNumber).css('width', '100%');
			$('#filename' + thisAttachmentNumber).css('background-color', 'green');
		}
	});

Is this a bug or have I done something wrong? Forgive me if I've not included enough information, just let me know what else I can provide.

**Comment by Abe-Froman** [comment]
I'm sorry I tried for 10 minutes to get the code blocks above formatted correctly but the text editor is smarter than me. This is my first post to GitHub. :(

**Comment by blackcity** [comment]
File chunking in not supported in the Standard Edition, you can only test it during development on a local machine:
https://github.com/blackcity/Backload/wiki/editions

Try to remove file chunking in the client side config and upload a not to big file. Does this work?

**Comment by Abe-Froman** [comment]
I believe that involves only commenting out the line from my view, `maxChunkSize: 50000000, // 50MB chunks`, correct? If so, the same error occurs.

The strange thing is I *thought* this was working a few days ago but couldn't confirm 100% so figured it was something I changed, I just can't find anything I changed that would have caused this.

Thanks for the quick reply btw!

**Comment by blackcity** [comment]
I assume GET requests are working correctly. Can you provide the Fiddler session for the request (save session)?
You can also enable tracing (see demo package, tracing example) and see where it breaks.

**Comment by Abe-Froman** [comment]
I've not had, nor will down the road, to need to use Backload for any GET, only POST so I haven't tried that. 

From debugging the w3wvc process on the server I can see that it breaks on `IBackloadResult result = await handler.Execute()`.

I added tracing according to Example 13 but I'm not getting any logs (assuming they should appear in _webroot_/Backload/Logs), though Demo 1 describes using the VS output window, this is what I see

    Backload Information: 10 : Backload component ({0}): Instance initialization started.
    Backload Information: 19 : CORS preflight request from origin . No further processing.
    Backload Information: 20 : Backload component ({0}): Instance initialization finished with success.
    Backload Information: 200 : Execution pipeline started.
    Backload Information: 300 : Initial configuration security checks started
    Backload Information: 399 : Initial configuration security checks passed with success.
    Backload Information: 600 : Execution of core POST method started.
    Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
    Backload Error: 163180 : Exception thrown: 'System.FormatException' in mscorlib.dll
    Exception thrown: 'System.FormatException' in mscorlib.dll
    Exception thrown: 'System.FormatException' in mscorlib.dll
    Exception thrown: 'System.FormatException' in mscorlib.dll
    Exception thrown: 'System.FormatException' in mscorlib.dll
    Exception thrown: 'System.FormatException' in mscorlib.dll
    Exception thrown: 'System.FormatException' in mscorlib.dll

Can you send me a location I could drop the Fiddler session for you? I can't attach it here.

**Comment by blackcity** [comment]
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll means that you do not have sufficient permissions for this folder.

You can upload the session file here:
https://script.google.com/macros/s/AKfycbxcIR4e8XibJCkV5-Nyy6govKMkd9PldvZus6NV0l_xeIuK2Is8/exec

**Comment by Abe-Froman** [comment]
Sorry for the long delay, I had a holiday over the weekend into the first part of this week.

The session file is dropped. I think you can disregard the UnauthorizedAccessException listed there, I am getting that all the time, even on GET requests not involving Backload, and have yet to troubleshoot that.

**Comment by Auersberg** [comment]
Thank you. I received to Fiddler session and I'll do some test tomorow.

It is important to get a trace log for the POST request.

With a WebPageTraceListener you can view the trace messages  online. This goes into the web.config (example from the latest demo package, trace demo):
<pre>
&lt;system.diagnostics&gt; 
    &lt;trace autoflush="true" /&gt;
    &lt;sources&gt; 
        &lt;!--TraceSource name must be "Backload". Valid levels are: Off, Critical, Warning, Information, Verbose. --&gt; 
        &lt;source name="Backload" switchvalue="Verbose"&gt;
        &lt;listeners&gt; 
            &lt;!--ASP.NET Trace listener. Trace output can be accessed at url http://[webapp root]/trace.axd--&gt; 
            &lt;add name="WebPageTraceListener" type="System.Web.WebPageTraceListener, System.Web, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" /&gt;
        &lt;/listeners&gt; 
        &lt;/source&gt; 
    &lt;/sources&gt; 
&lt;/system.diagnostics&gt; 
              
&lt;system.web&gt;
  &lt;trace enabled="true" mostrecent="true" requestlimit="50" localonly="false" /&gt;
  [...]
&lt;/system.web&gt;
</pre>

Web.Backload.config:
<pre>
&lt;backload tracing="true" [...]&gt;
  [more settings]
&lt;/backload&gt;
</pre>

Send your request, then open the following page, find the Ajax POST request and click details: 
http://[your web app]/trace.axd

**Comment by Abe-Froman** [comment]
A trace has been dropped now, thanks for the additional info I didn't know about the trace.axd page.

**Comment by Auersberg** [comment]
So, no trace output This is only the request info.
If you right click on Web.Backload.config file and select properties. Is Build Action set to Content?

**Comment by Abe-Froman** [comment]
Finally got tracing sorry about that. Had a typo in web.config. :(

Dropped the new trace.

**Comment by Abe-Froman** [comment]
And of course that tracing is helpful, it pointed out the problem which I've now resolved.

Apparently I disabled inheritance on the uploads folder at one point so the permissions I was setting on the root were not inherited on ~/Uploads.

I really appreciate your time, patience, and education with regards to the tracing. That will certainly allow me to self-serve down the road.
