### ISSUE TITLE
How to deal with this problem support mvc6 ?

### ISSUE THREAD

**Issue by Chinalirui** [blackcity/Backload#88]
IFileHandler handler = Backload.FileHandler.Create();
  handler.Init(this.Request);
this.Request is Microsoft.aspnet.http.httprequest 。
How to deal with this problem？

**Comment by blackcity** [comment]
While we are currently testing MVC6 and .NET core it is not officially supported in the current public release.
Internally, Backload uses the injected HttpWebRequest instance only to create a BackloadDataProvider instance. The demo package has a simple example in the CustomDataProvider demo. 

You can do the same of course with Microsoft.aspnet.http.httprequest Microsoft.aspnet.http.httprequest, create a BackloadDataProvider and inject it into the Init method, but this is not documented currently and so I do not know, if this helps you.

**Comment by Auersberg** [comment]
MVC6 preview package for ASP.NET 5 (release candidate) is available here:
https://github.com/blackcity/Backload/wiki/ASP.NET%205,%20MVC6,%20.NET%20Core
