### ISSUE TITLE
json result structure

### ISSUE THREAD

**Issue by mjmcginty** [blackcity/Backload#89]
We're upgrading from Standard v2.0.0.0 to Professional 2.1.5.5.  I'm now seeing a javascript error when it references data.result.files, "cannot read property 'files' of null."  I noticed there is now a data.files array, I tried changing my code, but jquery file modules reference it too.

I compared the jquery/blueimp files we are using, they are the same as on the .iso image.  I also checked the plugin setting, it wasn't present in our config (so defaulted to the correct setting.)  Not surprisingly, setting it to  plugin="JQueryFileUpload" had no affect.

Could it be because I'm manipulating results in my GetFilesRequestFinished handler?  (I clear e.Param.FileStatus.Files and then add one Backload.Status.FileStatusItem to it.)  The code worked as expected with the earlier version.

TIA,
Mark McGinty

**Comment by Auersberg** [comment]
Usually, a Json object with a files array like this for the JQuery File Upload Plugin is returned:
<pre>
{
	"files": [{
		"type": "image/tiff",
		"size": 450174760,
		"url": "http://localhost:18499/Uploads/C5F260DD3787/test_big.tif",
		"thumbnailUrl": "http://localhost:18499/Uploads/C5F260DD3787/_thumbs/test_big.tif.png",
		"deleteUrl": "http://localhost:18499/Backload/FileHandler?filename=test_big.tif\u0026objectContext=C5F260DD3787",
		"deleteType": "DELETE",
		"group": "",
		"name": "test_big4.tif",
		"uuid": "5deaa1e7-01d3-4887-91f7-7e9d6148db5d",
		"error": "",
		"success": true,
		"extra": {
			"originalName": "test_big.tif",
			"message": "",
			"errorCode": 0,
			"mainType": "image",
			"metaData": null,
			"chunkInfo": null
		}
	}]
}
</pre>

How does your json look like (use Fiddler).

**Comment by mjmcginty** [comment]
My bad, I missed the first digit when I copied the license key, it was returning a null response because it was throwing an invalid key exception.  Sorry to bug you for nothing.
