### ISSUE TITLE
Post processing event question

### ISSUE THREAD

**Issue by DaveDiest** [blackcity/Backload#90]
I need to store a file in a sub folder that is based on a date time stamp under the context folder. 

my first thought is to do this in a post event such as Events_StoreFileRequestFinished.

Since we are using chunked uploading I don't know when the last file chunk is uploaded and the file itself has been reassembled.

Is there an event that fires after the file has been reassembled?

Any other ideas and suggestions?

I need the date time to come from the server since we don’t want to trust the client clock.

**Comment by Auersberg** [comment]
Server side PostProcessing events are available, see current demo package, there is a post processing example. Post processing has been included in one of the last releases.
