### ISSUE TITLE
What event when finished upload process?

### ISSUE THREAD

**Issue by andrecesco** [blackcity/Backload#91]
Hi.
What would be the event when the upload process is finished?

Thanks.

**Comment by andrecesco** [comment]
The version of backload is standard

**Comment by Auersberg** [comment]
Server side or client side event?

Server side event may be this, but others available:
IFileHandler.Events.StoreFileRequestFinished

**Comment by andrecesco** [comment]
Auersberg ,

I Have a following situation.
I need after upload all files. The server side or client side report that ended upload all files.

You have a method for help me.

**Comment by Auersberg** [comment]
Only the client has the info that all files are uploaded. So use a client side event.

###### Pure client side handling:
<pre>
    var uploadFailed = false;

    // Initialize the jQuery File Upload widget:
    $('#fileupload').fileupload({
        url: url,
    })

    .bind('fileuploadstop', function (e) {
        // The 'fileuploadstop' event will be fired when uploads are finished, canceled or an error occured
        if (!uploadFailed) {
            // uploaded all files successfully
            alert("Uploaded all files");
        }
        uploadFailed = false;
    })

    .bind('fileuploadfail', function (e, data) {
        // The 'fileuploadfail' event will be fired if an upload is canceled or an error occured
       uploadFailed = true;
    });
</pre>

<br />
###### Additional server side post processing:
Whithin the client side event handler above you can also trigger the server side post processing event, 

Trigger server side processing (see demo package, post processing demo):
<pre>
    var sep = (url.indexOf('?') == -1) ? '?' : '&';
    var execute = 'execute=postprocess()';   // 2.2+ release. 2.1 is slightly different.
    var t = '&t=' + Math.random().toString(36).substr(2, 8);
    $.getJSON(url + sep + execute + t, function (result) {
        // Server side post processing result
    });
</pre>

On the server you just need to attach an event handler:
<pre>
handler.Events.PostProcessingStarted += Events_PostProcessingStarted;

private void Events_PostProcessingStarted(IFileHandler sender, Contracts.Eventing.IPostProcessingEventArgs e)
{
}
</pre>

**Comment by andrecesco** [comment]
That is it

Thanks Auersberg.
