### ISSUE TITLE
Overwriting server file

### ISSUE THREAD

**Issue by heldersepu** [blackcity/Backload#92]
When we upload a file if a file exists with the same name the file is overwritten.
Is there any option to prevent that?

**Comment by Auersberg** [comment]
There is a `uniqueFileNames` option you can set to true, so all files get a uuid as file name and cannot be overwritten. If you set `keepOrgFileNames`to true, the original file names are preserved.

Usage (Web.Backload.config):
<pre>
&lt;backload uniqueFileNames="true" keepOrgFileNames="true" [...]&gt;
&lt;/backload&gt;
</pre>

https://github.com/blackcity/Backload/wiki/Configuration#options-and-settings

**Comment by heldersepu** [comment]
Thanks
