### ISSUE TITLE
Event: StoreFileRequestFinished and chunking

### ISSUE THREAD

**Issue by DaveDiest** [blackcity/Backload#94]
Good day to you,

I need do something with a file that has been uploaded and i'm doing large file uploads and using chunking.    By the look of it the StoreFileReqeustFinished event fires after each chunk is saved.

I need a way to know when the file that is chunked has been reassembled and thus I can do something after that.

Thanks Much

**Comment by Auersberg** [comment]
You can use the StoreFileRequestFinished event:
<pre>
void Events_StoreFileRequestFinished(IFileHandler sender, Contracts.Eventing.IStoreFileRequestEventArgs e)
{
    var file = e.Param.FileStatusItem;

    if (file.StorageInfo.ChunkInfo.ChunksComplete)
    {
        // Do something
    }
}
</pre>

**Comment by DaveDiest** [comment]
Thanks and I have it working now.
