### ISSUE TITLE
Knowing when there is a license issue

### ISSUE THREAD

**Issue by DaveDiest** [blackcity/Backload#97]
Good Day,

I'm currently configuring the license.   I would like to know how we can tell if there is a license issue for example if We type it in wrong.

I was going copy copy pate from the PDF you sent my company but the mode of the PDF is blocking copy paste so I have to type it in.

Thanks

-Dave

**Comment by Auersberg** [comment]
If you enter a false key or the key is missing in the Pro Edition, a license exception occurs when the component inits. So, you will not be able to handle any request. If you set a breakpoint in the catch block you'll see a license exception.
