### ISSUE TITLE
done event  triggered twice

### ISSUE THREAD

**Issue by icernn03** [blackcity/Backload#99]
$('#fileupload').fileupload('option', 'done').call($('#fileupload'), $.Event('done'),
    {
       result:
          {
              files: {fileJson}
           }
   });

Im trying to display already uploaded files and files are rendered twice
Tested using alert and confirmed done event is triggered twice

**Comment by Auersberg** [comment]
You seem trying to create your own result object and add the files to the 
list (Basic Plus UI theme?). Can you explain why you do it this way? Have 
your tried out the code provided in the [demos](https://github.com/blackcity/Backload/blob/master/Examples/Backload.Standard.2.2/Backload.FileSystem.Demo.zip?raw=true)?

Your code snippet doesn't show what else you do in your Javascript code. 
Can you provide a simplified example of your client side code?

**Comment by icernn03** [comment]
Im using file uploader in a request form which the users can come back and continue anytime
that is why I need to display files they have already uploaded.
Im using file uploader in a c# mvc project
files display twice when I come back to continue the form or if i refresh the page
somehow done event is triggered twice confirmed using alert function
I did not attach done event anywhere else

here is my code
$('#fileupload').fileupload();
$('#fileupload').fileupload('option', {
        url: '@Url.Action("Create","File")',
        maxFileSize: 500000000,
        resizeMaxWidth: 1920,
        resizeMaxHeight: 1200,
        autoUpload: false,
        submit: function(e, data) {
            var inputs = data.context.find(':input');
            if (inputs.filter(function() {
                return !this.value && $(this).prop('required');
            }).first().focus().length) {
                data.context.find('button').prop('disabled', false);
                return false;
            }
        },
        acceptFileTypes: /(\.|\/)(gif|jpe?g|png|pdf)$/i,
    // Enable image resizing, except for Android and Opera,
    // which actually support image resizing, but fail to
    // send Blob objects via XHR requests:
            disableImageResize: /Android(?!.*Chrome)|Opera/
                .test(window.navigator.userAgent),
        previewMaxWidth: 100,
        previewMaxHeight: 100,
        previewCrop: true
 });

then I attach done event only if user has already uploaded any files

**Comment by Auersberg** [comment]
I've just tested it successfully using the following Javascript code:
<pre>
// Initialize the jQuery File Upload widget:
$('#fileupload').fileupload({
    url: url,
    acceptFileTypes: /(jpg)|(jpeg)|(png)|(gif)|(tif)|(pdf)$/i                  // Allowed file types
});

$('#fileupload').fileupload('option', 'done').call($('#fileupload'), $.Event('done'),
{
    result:
    {
        files:  [
        {
            name: "test.jpg",
            size: 1000000,
            type: "image/jpg",
            extra: { originalName: "test.jpg" },
            url: "http://lab7.backload.org/app15/files/test.jpg",
            thumbnailUrl: "http://lab7.backload.org/app15/files/previews/test.jpg.png",
            deleteUrl: "http://lab7.backload.org/app15/Backload/FileHandler?fileName=test.jpg"
        }]
    }
});
</pre>

I think your problem is not in this part of code.

**Comment by icernn03** [comment]
Hi Thanks for your response but I have script included only once in the layout page
and plugin  instantiated in the view
I have tried including script in the view instead but it is still the same
I just want to know what could possibly arise this issue

**Comment by Auersberg** [comment]
What happens, when you pull the list of existing files in an AJAX request like in the demos:
https://github.com/blackcity/Backload/blob/master/Examples/Backload.Standard.2.1.Full/Backload.Demo/Scripts/demos.blueimp.basicplusui.js

Is this working?

**Comment by icernn03** [comment]
tried. Ajax request is triggered twice
I have checked if it is a jquery error but the issue arise only in pages where i have used file upload.

**Comment by icernn03** [comment]
Im sorry I forgot to tell I was implementing file upload with jquery steps since file upload is the last step in form submission.
I moved file upload out of container used for jquery steps and it works just fine
Have you any idea why jquery steps is causing it
Thank you very much

**Comment by icernn03** [comment]
I have fixed it by attaching done event after jquery steps is initialized.
thank you for your help

**Comment by Auersberg** [comment]
Thanks for providing your solution. 

I also did a basic test with jQuery.Steps and it seems to work with the file upload plugin when Steps is initialized first. So, same result as you provided.
